import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'


export const metadata: Metadata = {
  title: 'Nxt13',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="justify-start items-start sm:px-44 px-20 flex flex-col min-h-screen py-2 bg-gray-50 sm:py-6 lg:py-8">{children}</body>
    </html>
  )
}
